apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: pataradzma
  namespace: default
spec:
  replicas: 3
  strategy:
    canary:
      steps:
        - setWeight: 100
        - pause: {}
  selector:
    matchLabels:
      app: pataradzma
  template:
    metadata:
      labels:
        app: pataradzma
    spec:
      containers:
        - name: pataradzma
          image: nginx:1.27.0
          ports:
            - containerPort: 80
